name: autostart_settings
description: "Plugin to check if autostart settings is available for the device and opens the autostart settings"
version: 0.1.3
repository: https://github.com/chris-wolf/autostart_settings

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  plugin:
    platforms:
      android:
        package: dev.cwolf.autostartSettings.autostart_settings
        pluginClass: AutostartSettingsPlugin

screenshots:
  - description: 'Xiaomi autostart settings'
    path: example/screenshots/autostart_settings_xiaomi.png
